javac a3\*.java 
javac myGameEngine\*.java
javac NetworkingServer\*.java
javac ray\*.java
javac ray\*\*.java
javac ray\*\*\*.java
javac ray\*\*\*\*.java
javac ray\*\*\*\*\*.java
javac ray\*\*\*\*\*\*.java
javac ray\*\*\*\*\*\*\*.java